-- MySQL Script generated by MySQL Workbench
-- 08/07/15 10:37:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mock_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mock_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mock_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mock_db` ;

-- -----------------------------------------------------
-- Table `mock_db`.`User_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mock_db`.`User_Type` (
  `user_type_id` INT NOT NULL AUTO_INCREMENT,
  `user_type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mock_db`.`R_F_O_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mock_db`.`R_F_O_User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `enabled` TINYINT(1) NOT NULL,
  `user_type_id` INT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_User_User_Type_idx` (`user_type_id` ASC),
  CONSTRAINT `fk_User_User_Type`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `mock_db`.`User_Type` (`user_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mock_db`.`Agreement_Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mock_db`.`Agreement_Status` (
  `agreement_status_id` INT NOT NULL AUTO_INCREMENT,
  `agreement_status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`agreement_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mock_db`.`Agreements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mock_db`.`Agreements` (
  `agreement_number` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `variant_number` INT NOT NULL,
  `agreement_name` VARCHAR(100) NOT NULL,
  `description` TEXT(1000) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `is_sign_required` TINYINT(1) NOT NULL,
  `funding_method` VARCHAR(45) NOT NULL,
  `payment_to` VARCHAR(45) NOT NULL,
  `agenda_payment` VARCHAR(45) NOT NULL,
  `handling_charge` DOUBLE NOT NULL,
  `dealer_visibility` VARCHAR(45) NOT NULL,
  `volume_discount_type` VARCHAR(45) NOT NULL,
  `discount_unit` VARCHAR(45) NOT NULL,
  `combinability` VARCHAR(45) NOT NULL,
  `status_id` INT NOT NULL,
  `is_sign_received` TINYINT(1) NULL,
  `authorised_by` VARCHAR(45) NULL,
  `created_by` VARCHAR(45) NULL,
  `number_of_registrations` INT NULL,
  `sign_received_date` DATETIME NULL,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  `last_updated_date` DATETIME NULL,
  INDEX `fk_Agreements_User1_idx` (`user_id` ASC),
  INDEX `fk_Agreements_Agreement_Status1_idx` (`status_id` ASC),
  PRIMARY KEY (`agreement_number`),
  CONSTRAINT `fk_Agreements_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mock_db`.`R_F_O_User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agreements_Agreement_Status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `mock_db`.`Agreement_Status` (`agreement_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mock_db`.`Credit_Node_Text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mock_db`.`Credit_Node_Text` (
  `credit_node_text_id` INT NOT NULL AUTO_INCREMENT,
  `agreement_number` INT NOT NULL,
  `variant_number` INT NULL,
  `credit_note` VARCHAR(255) NULL,
  `justification` VARCHAR(255) NOT NULL,
  `date_time` DATETIME NOT NULL,
  PRIMARY KEY (`credit_node_text_id`),
  INDEX `fk_Credit_Node_Text_Agreements1_idx` (`agreement_number` ASC),
  CONSTRAINT `fk_Credit_Node_Text_Agreements1`
    FOREIGN KEY (`agreement_number`)
    REFERENCES `mock_db`.`Agreements` (`agreement_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mock_db`.`Customer_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mock_db`.`Customer_Type` (
  `customer_type_id` INT NOT NULL AUTO_INCREMENT,
  `customer_type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mock_db`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mock_db`.`Company` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(45) NOT NULL,
  `company_type` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `sector` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `fax_number` VARCHAR(45) NULL,
  `email_address` VARCHAR(45) NULL,
  `business_area` VARCHAR(45) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mock_db`.`R_F_O_Number`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mock_db`.`R_F_O_Number` (
  `r_f_o_number` VARCHAR(45) NOT NULL,
  `r_f_o_name` VARCHAR(45) NOT NULL,
  `customer_type_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  INDEX `fk_RFO_Number_Customer_Type1_idx` (`customer_type_id` ASC),
  INDEX `fk_RFO_Number_Company1_idx` (`company_id` ASC),
  PRIMARY KEY (`r_f_o_number`),
  CONSTRAINT `fk_RFO_Number_Customer_Type1`
    FOREIGN KEY (`customer_type_id`)
    REFERENCES `mock_db`.`Customer_Type` (`customer_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RFO_Number_Company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `mock_db`.`Company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mock_db`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mock_db`.`Address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `address1` VARCHAR(255) NULL,
  `address2` VARCHAR(255) NULL,
  `address3` VARCHAR(255) NULL,
  `address4` VARCHAR(255) NULL,
  `address5` VARCHAR(255) NULL,
  `city` VARCHAR(45) NULL,
  `sate` VARCHAR(45) NULL,
  `country` VARCHAR(45) NOT NULL,
  `post_code` VARCHAR(45) NOT NULL,
  INDEX `fk_Address_Company1_idx` (`company_id` ASC),
  PRIMARY KEY (`address_id`),
  CONSTRAINT `fk_Address_Company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `mock_db`.`Company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mock_db`.`Agreement_R_F_O`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mock_db`.`Agreement_R_F_O` (
  `r_f_o_number` VARCHAR(45) NOT NULL,
  `agreement_number` INT NOT NULL,
  `variant_number` INT NOT NULL,
  INDEX `fk_Agreement_R_F_O_R_F_O_Number1_idx` (`r_f_o_number` ASC),
  INDEX `fk_Agreement_R_F_O_Agreements1_idx` (`agreement_number` ASC),
  PRIMARY KEY (`r_f_o_number`, `agreement_number`),
  CONSTRAINT `fk_Agreement_R_F_O_R_F_O_Number1`
    FOREIGN KEY (`r_f_o_number`)
    REFERENCES `mock_db`.`R_F_O_Number` (`r_f_o_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agreement_R_F_O_Agreements1`
    FOREIGN KEY (`agreement_number`)
    REFERENCES `mock_db`.`Agreements` (`agreement_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mock_db`.`Dealer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mock_db`.`Dealer` (
  `dealer_id` INT NOT NULL AUTO_INCREMENT,
  `dealer_code` VARCHAR(45) NOT NULL,
  `dealer_name` VARCHAR(45) NOT NULL,
  `town` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dealer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mock_db`.`Agreement_Dealer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mock_db`.`Agreement_Dealer` (
  `agreement_dealer` INT NOT NULL AUTO_INCREMENT,
  `agreement_number` INT NOT NULL,
  `dealer_id` INT NOT NULL,
  `variant_number` INT NULL,
  INDEX `fk_Agreement_Dealer_Dealer1_idx` (`dealer_id` ASC),
  PRIMARY KEY (`agreement_dealer`),
  CONSTRAINT `fk_Agreement_Dealer_Dealer1`
    FOREIGN KEY (`dealer_id`)
    REFERENCES `mock_db`.`Dealer` (`dealer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agreement_Dealer_Agreements1`
    FOREIGN KEY (`agreement_number`)
    REFERENCES `mock_db`.`Agreements` (`agreement_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mock_db`.`Volume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mock_db`.`Volume` (
  `volume_id` INT NOT NULL AUTO_INCREMENT,
  `agreement_number` INT NOT NULL,
  `trigger_credit` VARCHAR(45) NOT NULL,
  `payment_to` VARCHAR(45) NOT NULL,
  `variant_number` INT NULL,
  PRIMARY KEY (`volume_id`),
  INDEX `fk_Volume_Agreements1_idx` (`agreement_number` ASC),
  CONSTRAINT `fk_Volume_Agreements1`
    FOREIGN KEY (`agreement_number`)
    REFERENCES `mock_db`.`Agreements` (`agreement_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mock_db`.`Banding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mock_db`.`Banding` (
  `banding_id` INT NOT NULL AUTO_INCREMENT,
  `volume_id` INT NOT NULL,
  `min` INT NOT NULL,
  `max` INT NOT NULL,
  PRIMARY KEY (`banding_id`),
  INDEX `fk_Banding_Volume1_idx` (`volume_id` ASC),
  CONSTRAINT `fk_Banding_Volume1`
    FOREIGN KEY (`volume_id`)
    REFERENCES `mock_db`.`Volume` (`volume_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mock_db`.`System_Config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mock_db`.`System_Config` (
  `system_config_id` INT NOT NULL AUTO_INCREMENT,
  `config_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`system_config_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mock_db`.`System_Config_Value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mock_db`.`System_Config_Value` (
  `system_config_value_id` INT NOT NULL AUTO_INCREMENT,
  `system_config_id` INT NOT NULL,
  `config_value` VARCHAR(45) NOT NULL,
  `order` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`system_config_value_id`),
  INDEX `fk_System_Config_Value_System_Config1_idx` (`system_config_id` ASC),
  CONSTRAINT `fk_System_Config_Value_System_Config1`
    FOREIGN KEY (`system_config_id`)
    REFERENCES `mock_db`.`System_Config` (`system_config_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
